function imagesc_subplot(cdata1, cdata2, cdata3)
%CREATEFIGURE(cdata1, cdata2, cdata3)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  CDATA3:  image cdata

%  Auto-generated by MATLAB on 28-Feb-2023 23:54:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0447091743499528 0.130434782608696 0.246957492316714 0.804017013232517]);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create ylabel
ylabel('Stimulus Event Number');

% Create xlabel
xlabel('Time After Light Stimulus (s)');

% Create title
title('1st Light Only');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 40.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 55.5]);
box(axes1,'on');
axis(axes1,'ij');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Layer','top','XTick',[4 8 12 16 20 24 28 32 36 40],'XTickLabel',...
    ['1 ';'2 ';'3 ';'4 ';'5 ';'6 ';'7 ';'8 ';'9 ';'10'],'YTick',...
    [0 5 10 15 20 25 30 35 40 45 50 55 60]);
% Create colorbar
colorbar(axes1,'Position',...
    [0.297661743904614 0.128252788104089 0.0112517580872011 0.804832713754647]);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.356742203884726 0.126654064272212 0.251907585144809 0.812854442344045]);
hold(axes2,'on');

% Create image
image(cdata2,'Parent',axes2,'CDataMapping','scaled');

% Create ylabel
ylabel('Stimulus Event Number');

% Create xlabel
xlabel('Time After Light Stimulus (s)');

% Create title
title('Light + US');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.5 40.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.5 52.5]);
box(axes2,'on');
axis(axes2,'ij');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'Layer','top','XTick',[4 8 12 16 20 24 28 32 36 40],'XTickLabel',...
    ['1 ';'2 ';'3 ';'4 ';'5 ';'6 ';'7 ';'8 ';'9 ';'10'],'YTick',...
    [0 5 10 15 20 25 30 35 40 45 50 55 60]);
% Create colorbar
colorbar(axes2);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.678230728076722 0.120817843866171 0.26533467276716 0.81750953963781]);
hold(axes3,'on');

% Create image
image(cdata3,'Parent',axes3,'CDataMapping','scaled');

% Create ylabel
ylabel('Stimulus Event Number');

% Create xlabel
xlabel('Time After Light Stimulus (s)');

% Create title
title('2nd Light Only');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0.5 40.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0.5 57.5]);
box(axes3,'on');
axis(axes3,'ij');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'Layer','top','XTick',[4 8 12 16 20 24 28 32 36 40],'XTickLabel',...
    ['1 ';'2 ';'3 ';'4 ';'5 ';'6 ';'7 ';'8 ';'9 ';'10'],'YTick',...
    [0 5 10 15 20 25 30 35 40 45 50 55 60]);
% Create colorbar
colorbar(axes3,'Position',...
    [0.949369286098706 0.120817843866171 0.0112517580872011 0.814126394052044]);

